name: Detect Context Output Vulnerability

on: 
  issues: 
    types: [opened, edited]

jobs:
  job1:
    uses: ./.github/workflows/reusableWorkflow.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}"
