name: Detect Context Sink Vulnerability

on: 
  issues: 
    types: [opened, edited]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log the issue's title
        env: 
          TITLE: ${{ github.event.issue.title }}
        run: |
          echo "A new pull request was created with the 
          title $TITLE"
