name: Detect Context Output Vulnerability

on: 
  issues: 
    types: [opened, edited]

jobs:
    example_job:
      name: Generate output
      runs-on: ubuntu-latest
      # Map the job outputs to step outputs
      outputs:
        output1: ${{ steps.step1.outputs.firstword }}
        output2: ${{ steps.step2.outputs.secondword }}
      steps:
      - id: step1
        run: echo "firstword=${{ github.event_name }}" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT  
