name: Detect Context Sink Vulnerability

on: 
  issues: 
    types: [opened, edited]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log the issue's title
        run: |
          echo "The argument passed into the workflow is ${{ github.event_name }}" 
